insert into metric_system (id, pattern) values ('met', '((Х|Я|Д|Ам|Ан|Дк|Т|Пн(I|II|III|IV))[4-8]+|Рк|Гк|Эд|Пт)(ц.[пн].[12])');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'Х', 'хорей');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'Я', 'ямб');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'Д', 'дактиль');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'Ам', 'амфибрахий');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'Ан', 'анапест');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'Дк', 'дольник');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'T', 'тактовик');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'ПнI', 'пеон I');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'ПнII', 'пеон II');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'ПнIII', 'пеон III');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'ПнIV', 'пеон IV');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'Рк', 'раешник');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'Гк', 'гекзаметр');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'Эд', 'элегический дистих');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'Пт', 'пентаметр');
  insert into metric_elements (sys_id, id, interpretation) values ('met', '4', 'четырехстопный');
  insert into metric_elements (sys_id, id, interpretation) values ('met', '5', 'пятистопный');
  insert into metric_elements (sys_id, id, interpretation) values ('met', '6', 'шестистопный');
  insert into metric_elements (sys_id, id, interpretation) values ('met', '7', 'семистопный');
  insert into metric_elements (sys_id, id, interpretation) values ('met', '8', 'восьмистопный');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'ц.н.1', 'с цезурным наращением на один слог');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'ц.н.2', 'с цезурным наращением на два слога');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'ц.у.1', 'с цезурным усечением на один слог');
  insert into metric_elements (sys_id, id, interpretation) values ('met', 'ц.у.2', 'с цезурным усечением на два слога');
insert into metric_system (id, pattern) values ('rhyme', '[abcdxABCDX]''?''?)+\.?');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'a', 'рифмованный стих с мужским окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'A', 'рифмованный стих с женским окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'A''', 'рифмованный стих с дактилическим окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'A''''', 'рифмованный стих с гипердактилическим окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'b', 'рифмованный стих с мужским окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'B', 'рифмованный стих с женским окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'b''', 'рифмованный стих с дактилическим окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'B''''', 'рифмованный стих с гипердактилическим окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'c', 'рифмованный стих с мужским окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'C', 'рифмованный стих с женским окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'C''', 'рифмованный стих с дактилическим окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'C''''', 'рифмованный стих с гипердактилическим окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'd', 'рифмованный стих с мужским окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'D', 'рифмованный стих с женским окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'D''', 'рифмованный стих с дактилическим окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'D''''', 'рифмованный стих с гипердактилическим окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'x', 'нерифмованный стих с мужским окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'X', 'нерифмованный стих с женским окончанием');
  insert into metric_elements (sys_id, id, interpretation) values ('rhyme', 'X''', 'нерифмованный стих с дактилическим окончанием');
