insert into text_pictures (text_id, kind, url) values ('texts/Призывание_и_явление_Плениры.tei', 'leading', '/images/figures/derjavin/1/bastidon.gif');
insert into text_pictures (text_id, kind, url) values ('texts/Фелица.tei', 'leading', '/images/figures/derjavin/1/ekaterina1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/отрок.tei', 'leading', '/images/figures/derjavin/1/alexander.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/отрок.tei', 'leading', '/images/figures/derjavin/1/20.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/видение_мурзы.tei', 'leading', '/images/figures/derjavin/1/ekaterina2.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Осень_во_время_осады_Очаково._Разметка.tei', 'leading', '/images/figures/derjavin/1/ochakov1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Осень_во_время_осады_Очаково._Разметка.tei', 'leading', '/images/figures/derjavin/1/ochakov2.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Снигирь._Разметка.tei', 'leading', '/images/figures/derjavin/1/suvorov.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Ода_на_взятие_Измаила.tei', 'leading', '/images/figures/derjavin/1/izmail.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/жизнь_Званская.tei', 'leading', '/images/figures/derjavin/1/eugeniy.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/похвала_сельской_жизни.tei', 'leading', '/images/figures/derjavin/1/horatius.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Сафо.tei', 'leading', '/images/figures/derjavin/1/sapho.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Прогулка_в_Сарском_Селе.tei', 'leading', '/images/figures/derjavin/1/tsarskoye.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Кружка.tei', 'inline', '/images/figures/derjavin/2/PICT0003-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Кружка.tei', 'trailing', '/images/figures/derjavin/2/PICT0004-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Ключ._Разметка.tei', 'inline', '/images/figures/derjavin/2/PICT0005-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Ключ._Разметка.tei', 'trailing', '/images/figures/derjavin/2/PICT0006-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/отрок.tei', 'inline', '/images/figures/derjavin/2/PICT0007-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/отрок.tei', 'trailing', '/images/figures/derjavin/2/PICT0008-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/На_смерть_кн._Мещерского.tei', 'inline', '/images/figures/derjavin/2/PICT0009-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/К_первому_соседу.tei', 'inline', '/images/figures/derjavin/2/PICT0010-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Властителям_и_судиям.tei', 'inline', '/images/figures/derjavin/2/PICT0012-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Фелица.tei', 'inline', '/images/figures/derjavin/2/PICT0013-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Фелица.tei', 'trailing', '/images/figures/derjavin/2/PICT0014-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Бог.tei', 'inline', '/images/figures/derjavin/2/PICT0017-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/На_смерть_Румянцовой.tei', 'inline', '/images/figures/derjavin/2/PICT0018-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Осень_во_время_осады_Очаково._Разметка.tei', 'inline', '/images/figures/derjavin/2/PICT0019-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/На_Счастие.tei', 'inline', '/images/figures/derjavin/2/PICT0020-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/На_Счастие.tei', 'trailing', '/images/figures/derjavin/2/PICT0022-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Ода_на_взятие_Измаила.tei', 'inline', '/images/figures/derjavin/2/PICT0035-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Ода_на_взятие_Измаила.tei', 'trailing', '/images/figures/derjavin/2/PICT0027-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Прогулка_в_Сарском_Селе.tei', 'inline', '/images/figures/derjavin/2/PICT0029-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Ко_второму_соседу.tei', 'inline', '/images/figures/derjavin/2/PICT0031-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Ко_второму_соседу.tei', 'trailing', '/images/figures/derjavin/2/PICT0032-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/водопад.tei', 'inline', '/images/figures/derjavin/2/PICT0035-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/водопад.tei', 'trailing', '/images/figures/derjavin/2/PICT0037-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Храповицкому._Разметка.tei', 'inline', '/images/figures/derjavin/2/PICT0038-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Храповицкому._Разметка.tei', 'trailing', '/images/figures/derjavin/2/PICT0040-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Ласточка.tei', 'inline', '/images/figures/derjavin/2/PICT0043-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/К_лире.tei', 'inline', '/images/figures/derjavin/2/PICT0044-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/К_лире.tei', 'trailing', '/images/figures/derjavin/2/PICT0047-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Мой_истукан.tei', 'inline', '/images/figures/derjavin/2/PICT0049-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Мой_истукан.tei', 'trailing', '/images/figures/derjavin/2/PICT0050-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Вельможа.tei', 'inline', '/images/figures/derjavin/2/PICT0053-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Приглашение_к_обеду.tei', 'inline', '/images/figures/derjavin/2/PICT0054-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Приглашение_к_обеду.tei', 'trailing', '/images/figures/derjavin/2/PICT0055-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Фелица.tei', 'inline', '/images/figures/derjavin/2/PICT0056-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Потопление.tei', 'inline', '/images/figures/derjavin/2/PICT0059-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Потопление.tei', 'trailing', '/images/figures/derjavin/2/PICT0061-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/памятникi.tei', 'inline', '/images/figures/derjavin/2/PICT0063-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/памятникi.tei', 'trailing', '/images/figures/derjavin/2/PICT0064-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/видение_мурзы.tei', 'inline', '/images/figures/derjavin/2/PICT0066-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/видение_мурзы.tei', 'trailing', '/images/figures/derjavin/2/PICT0068-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Призывание_и_явление_Плениры.tei', 'inline', '/images/figures/derjavin/2/PICT0070-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Призывание_и_явление_Плениры.tei', 'inline', '/images/figures/derjavin/2/PICT0071-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Сафо.tei', 'inline', '/images/figures/derjavin/2/PICT0073-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Сафо.tei', 'trailing', '/images/figures/derjavin/2/PICT0074-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Храповицкому._Разметка.tei', 'inline', '/images/figures/derjavin/2/PICT0075-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Храповицкому._Разметка.tei', 'trailing', '/images/figures/derjavin/2/PICT0076-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/дар.tei', 'inline', '/images/figures/derjavin/2/PICT0077-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/дар.tei', 'trailing', '/images/figures/derjavin/2/PICT0078-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Развалины._Разметка.tei', 'inline', '/images/figures/derjavin/2/PICT0079-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Развалины._Разметка.tei', 'inline', '/images/figures/derjavin/2/PICT0080-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Развалины._Разметка.tei', 'trailing', '/images/figures/derjavin/2/PICT0081-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/К_лире.tei', 'inline', '/images/figures/derjavin/2/PICT0082-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/К_лире.tei', 'trailing', '/images/figures/derjavin/2/PICT0084-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Урна.tei', 'inline', '/images/figures/derjavin/2/PICT0086-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Урна.tei', 'trailing', '/images/figures/derjavin/2/PICT0089-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/похвала_сельской_жизни.tei', 'inline', '/images/figures/derjavin/2/PICT0090-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/похвала_сельской_жизни.tei', 'trailing', '/images/figures/derjavin/2/PICT0092-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/К_самому_себе.tei', 'inline', '/images/figures/derjavin/2/PICT0094-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/К_самому_себе.tei', 'trailing', '/images/figures/derjavin/2/PICT0096-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Венец_бессмертия.tei', 'inline', '/images/figures/derjavin/2/PICT0099-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Венец_бессмертия.tei', 'trailing', '/images/figures/derjavin/2/PICT0100-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Русские_девушки.tei', 'inline', '/images/figures/derjavin/2/PICT0102-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Русские_девушки.tei', 'trailing', '/images/figures/derjavin/2/PICT0103-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/На_победы_в_Италии.tei', 'inline', '/images/figures/derjavin/2/PICT0105-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/На_победы_в_Италии.tei', 'trailing', '/images/figures/derjavin/2/PICT0107-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Снигирь._Разметка.tei', 'inline', '/images/figures/derjavin/2/PICT0109-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Снигирь._Разметка.tei', 'trailing', '/images/figures/derjavin/2/PICT0111-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Шуточное_желание.tei', 'inline', '/images/figures/derjavin/2/PICT0114-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Шуточное_желание.tei', 'trailing', '/images/figures/derjavin/2/PICT0117-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Свобода.tei', 'inline', '/images/figures/derjavin/2/PICT0118-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Свобода.tei', 'trailing', '/images/figures/derjavin/2/PICT0121-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Весна.tei', 'inline', '/images/figures/derjavin/2/PICT0123-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Лебедь.tei', 'inline', '/images/figures/derjavin/2/PICT0124-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Лебедь.tei', 'trailing', '/images/figures/derjavin/2/PICT0127-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Зима.tei', 'inline', '/images/figures/derjavin/2/PICT0129-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Зима.tei', 'trailing', '/images/figures/derjavin/2/PICT0133-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Осень2.tei', 'inline', '/images/figures/derjavin/2/PICT0135-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/жизнь_Званская.tei', 'inline', '/images/figures/derjavin/2/PICT0137-1.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Недоросль.tei', 'leading', '/images/figures/fonvizin/nedorosl_titlepage_1783.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/К_Панину-1.tei', 'leading', '/images/figures/fonvizin/panin.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/К_Панину_2.tei', 'leading', '/images/figures/fonvizin/panin.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/К_Панину_-3.tei', 'leading', '/images/figures/fonvizin/panin.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Письмо_4.tei', 'leading', '/images/figures/fonvizin/panin.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Письмо_5.tei', 'leading', '/images/figures/fonvizin/panin.jpg');
insert into text_pictures (text_id, kind, url) values ('texts/Письмо_6.tei', 'leading', '/images/figures/fonvizin/panin.jpg');

insert into text_pictures (text_id, url, kind, sortkey) values ($$texts/Димитрий.tei$$, $$/images/figures/sumarokov/dmitry1.jpg$$, $$leading$$, 2);
insert into text_pictures (text_id, url, kind, sortkey) values ($$texts/Димитрий.tei$$, $$/images/figures/sumarokov/dmitry2.jpg$$, $$leading$$, 1);
insert into text_pictures (text_id, url, kind, sortkey) values ($$texts/Димитрий.tei$$, $$/images/figures/sumarokov/dmitry3.jpg$$, $$trailing$$, 1);
insert into text_pictures (text_id, url, kind, sortkey) values ($$texts/Димитрий.tei$$, $$/images/figures/sumarokov/dmitry4.jpg$$, $$trailing$$, 2);


insert into text_pictures (text_id, url, kind) values ($$texts/Хорев.tei$$, $$/images/figures/sumarokov/horev1.jpg$$, $$leading$$);

insert into text_pictures (text_id, url, kind) values ($$texts/Синав_и_Трувор.tei$$, $$/images/figures/sumarokov/sinav.jpg$$, $$leading$$);

insert into text_pictures (text_id, url, kind) values ($$texts/Семира.tei$$, $$/images/figures/sumarokov/semira.jpg$$, $$leading$$);

insert into text_pictures (text_id, url, kind, sortkey) values ($$texts/Карамзин_Бедная_Лиза.tei$$, $$/images/figures/karamzin/liza1.jpg$$, $$leading$$, 3);
insert into text_pictures (text_id, url, kind, sortkey) values ($$texts/Карамзин_Бедная_Лиза.tei$$, $$/images/figures/karamzin/liza2.jpg$$, $$trailing$$, 1);
insert into text_pictures (text_id, url, kind, sortkey) values ($$texts/Карамзин_Бедная_Лиза.tei$$, $$/images/figures/karamzin/liza3.jpg$$, $$leading$$, 2);

insert into text_pictures (text_id, url, kind, sortkey) values ($$texts/Карамзин_Бедная_Лиза.tei$$, $$/images/figures/karamzin/mz1.jpg$$, $$leading$$, 1);

insert into text_pictures (text_id, url, kind, sortkey) values ($$texts/Карамзин_Прогулка.tei$$, $$/images/figures/karamzin/dt.jpg$$, $$leading$$, 1);
insert into text_pictures (text_id, url, kind, sortkey) values ($$texts/Карамзин_Прогулка.tei$$, $$/images/figures/karamzin/progulka1.jpg$$, $$trailing$$, 1);

insert into text_pictures (text_id, url, kind, sortkey) values ($$texts/Карамзин_Наталья.tei$$, $$/images/figures/karamzin/mz2.jpg$$, $$leading$$, 1);
insert into text_pictures (text_id, url, kind, sortkey) values ($$texts/Карамзин_Наталья.tei$$, $$/images/figures/karamzin/natalia1.jpg$$, $$trailing$$, 1);
