#! /bin/bash
shopt -s nullglob
set -u

declare -A temp_nodes
declare -A variables

nsRDF="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
nsRDFS="http://www.w3.org/2000/01/rdf-schema#"
nsOWL="http://www.w3.org/2002/07/owl#"
nsDCTERMS="http://purl.org/dc/terms/"
nsDCTYPE="http://purl.org/dc/dcmitype/"
nsDCAM="http://purl.org/dc/dcam/"

RDFSTORE="${RDFSTORE:-}"

generate_blank()
{
    mkdir -p $RDFSTORE/blanks/$$
    echo "$$$(basename $(mktemp --tmpdir=$RDFSTORE/blanks/$$ XXXXXXXX))"
}

encode_name()
{
    case "$1" in
        _)
            echo "$(generate_blank)"
            ;;
        _:*)
            if test -z "${temp_nodes[$1]:-}"; then
                temp_nodes[$1]="$(generate_blank)"
            fi
            echo "${temp_nodes[$1]}";
            ;;
        *)
            echo -n "$1" | sha1sum | cut -f1 -d' '
            ;;
    esac
}

indexed_name()
{
    echo ${1:0:1}/${1:1:1}/$1
}

make_object()
{    
    local name="$(encode_name "$1")"
    local path="$RDFSTORE/$(indexed_name $name)"
    if ! test -d $path; then
        mkdir -p $path  || { echo "Cannot create $path"; exit 1; }
        case "$1" in
            __:*)
                echo "__:$name" >$path/id
                ;;
            *)
                echo "$1" > $path/id
                ;;
        esac
        case "$1" in
            \"*\"*)
                echo >$path/literal
                ;;
        esac
        mkdir $path/in
        mkdir $path/out
        mkdir $path/subj
        mkdir $path/obj
    fi
    echo "$name"
}

get_object()
{
    cat "$RDFSTORE/$(indexed_name $1)/id"
}

make_triplet()
{
    local subjpath="$(indexed_name $1)"
    local predpath="$(indexed_name $2)"
    local objpath="$(indexed_name $3)"
    mkdir -p $RDFSTORE/$subjpath/out/$2/$3
    mkdir -p $RDFSTORE/$objpath/in/$2/$subjpath
    mkdir -p $RDFSTORE/$predpath/subj/$subjpath
    mkdir -p $RDFSTORE/$predpath/obj/$objpath
}

replace_var()
{
    case "$1" in
        _:*)
            if test -n "${variables[$1]}"; then
                echo "${variables[$1]}"
            else
                echo "$1"
            fi
            ;;
        *)
            echo "$1"
            ;;
    esac
}

contains_triplet()
{
    local path="$RDFSTORE/$(indexed_name $1)/out/$2/$3"
    test -d $path
}

is_literal()
{
    local path="$RDFSTORE/$(indexed_name $1)/literal"
    test -f $path
}

is_in_namespace()
{
    case "$(get_object $2)" in
        "<$1*>")
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

list_objects()
{
    local subj="$(indexed_name $1)"
    ls $RDFSTORE/$subj/out/$2
}

list_subjects()
{
    local obj="$(indexed_name $1)"
    local c1 c2
    for c1 in $RDFSTORE/$obj/in/$pred/?; do
        for c2 in $c1/?; do
            ls $c1/$c2
        done
    done
}

list_properties()
{
    local subj="$(indexed_name $1)"
    local p;
    for p in $(ls $RDFSTORE/$subj/out); do
        test -d $p/$2 && echo $(basename $p
    done
}

objRDF_type=$(make_object "<$nsRDF#type>")
objRDF_Property=$(make_object "<$nsRDF#Property>")
objRDFS_Class=$(make_object "<$nsRDFS#Class>")
objOWL_disjointWith=$(make_object "<$nsOWL#disjointWith>")

check_triplet()
{
    if test -n "$CHECK_DEFINED"; then
        if ! contains_triplet "$2" $objRDF_type $objRDF_Property; then
            echo "$(get_object $2) is not a Property" >&2
            exit 1
        fi
        if ! is_literal "$3" && ! is_in_namespace "$nsXSD#" "$3"; then
            if ! contains_triplet "$3" $objRDF_type $objRDF_Class &&
                ! contains_triplet "$3" $objRDF_type $objRDFS_Datatype; then
                echo "$(get_object $3) is not a Class" >&2
                exit 1
            fi
        fi
    fi

    if test -n "$CHECK_OWL"; then
        if test "$2" = $objRDF_type; then
            for cls in $(list_objects "$1" $objRDF_type); do
                if contains_triplet "$cls" $objOWL_disjointWith "$3" ||
                    contains_triplet "$3"  $objOWL_disjointWith "$cls"; then
                    echo "$(get_object $3) must be disjoint with $(get_object $cls)" >&2
                    exit 1
                fi
            done
        elif test "$2" = $objOWL_disjointWith; then
        fi
        if contains_triplet "$2" $objRDF_type $objOWL_FunctionalProperty; then
            local ex="$(list_objects "$1" "$2")"
            if test -n "$ex" -a "$ex" != "$3"; then
                echo "Functional constraint violated for $(get_object $1) $(get_object $2) $(get_object $3)" >&2
                exit 1
            fi
        fi
        if contains_triplet "$2" $objRDF_type $objOWL_InverseFunctionalProperty; then
            local ex="$(list_subjects "$3" "$2")"
            if test -n "$ex" -a "$ex" != "$1"; then
                echo "Inverse functional constraint violated for $(get_object $1) $(get_object $2) $(get_object $3)" >&2
                exit 1
            fi
        fi
    fi
}

entail_triplets()
{
    return 0
}

add_triplet()
{
    if ! contains_triplet "$@"; then
        check_triplet "$@"
        make_triplet "$@"
        entail_triplets "$@"
    fi
}

usage()
{
    cat >&2 <<EOF
Syntax: $(basename $0) [--db=STORE] OPERATION ARGS
where OPERATION is one of:
      add SUBJECT PREDICATE OBJECT ...
      parse PARSE-OPTIONS
EOF
}

CHECK_DEFINED=
CHECK_OWL=
ENTAIL_RDF=
ENTAIL_RDFS=
ENTAIL_DATATYPE=
ENTAIL_OWL=

while test $# -gt 0; do
    arg="$1"
    case "$arg" in
        -*)
            ;;
        *)
            break
            ;;
    esac
    shift
    case "$arg" in
        -d*)
            RDFSTORE="${arg#-d}"
            ;;
        --db\=*)
            RDFSTORE="${arg#--db=}"
            ;;
        --entail\=rdf)
            ENTAIL_RDF=1
            ;;
        --entail\=rdfs)
            ENTAIL_RDF=1
            ENTAIL_RDFS=1
            ;;
        --entail\=owl)
            ENTAIL_RDF=1
            ENTAIL_RDFS=1
            ENTAIL_OWL=1
            ;;
        --entail\=datatype)
            ENTAIL_DATATYPE=1
            ;;
        --check\=defined)
            CHECK_DEFINED=1
            ;;
        --check\=owl)
            CHECK_OWL=1
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        --)
            break
            ;;
        *)
            echo "Unknown option $arg" >&2
            usage
            exit 1
    esac
done

if test -z "$RDFSTORE"; then
    echo "No RDF store specified" >&2
    exit 1
fi

if test $# -eq 0; then
    echo "Command is missing" >&2
    usage
    exit 1
fi


op="$1"
shift

if test "$op" != "initialize" -a ! -d "$RDFSTORE"; then
    echo "RDF store $RDFSTORE does not exist; use 'initialize'" >&2
    exit 1
fi

case "$op" in
    initialize)
        mkdir -p $RDFSTORE
        ;;
    add)
        while test "$#" -gt 3; do            
            add_triplet "$1" "$2" "$3"
            shift 3
        done
        test "$#" -eq 0 || { echo "Incomplete triplet: $*" >&2; exit 1; }
        ;;
    parse)
        rapper -o ntriples "$@" | 
        while read subject predicate object; do
            add_triplet "$subject" "$predicate" "${object% .}"
        done
        ;;
    dump)
        for s1 in $RDFSTORE/?; do
            for s2 in $s1/?; do
                for subj in $s2/*; do
                    for pred in $subj/out/*; do
                        for obj in $pred/*; do
                            echo "$(< $subj/id) $(< $RDFSTORE/$(indexed_name $(basename $pred))/id) $(< $obj/id)"
                        done
                    done
                done
            done
        done
        ;;
    *)
        echo "Unknown command: $op" >&2
        usage
        exit 1
        ;;
esac